baseURL = "https://theredhare.github.io/"
languageCode = "en-us"
title = "Vagabond Security Research"
theme = "hugo-index"

[params]
  titleIcon = "index.png"
  buildSearchIndex = true

[taxonomies]
  tag = "tags"
  phase = "phase"
  services = "services"

[outputs]
  home = ["HTML", "JSON"]